#pragma warning disable 1591
//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HumaneSocietyProject
{
	using System.Data.Linq;
	using System.Data.Linq.Mapping;
	using System.Data;
	using System.Collections.Generic;
	using System.Reflection;
	using System.Linq;
	using System.Linq.Expressions;
	using System.ComponentModel;
	using System;
	
	
	[global::System.Data.Linq.Mapping.DatabaseAttribute(Name="Animals")]
	public partial class DataClasses1DataContext : System.Data.Linq.DataContext
	{
		
		private static System.Data.Linq.Mapping.MappingSource mappingSource = new AttributeMappingSource();
		
    #region Extensibility Method Definitions
    partial void OnCreated();
    partial void InsertAnimal(Animal instance);
    partial void UpdateAnimal(Animal instance);
    partial void DeleteAnimal(Animal instance);
    partial void InsertAdopter(Adopter instance);
    partial void UpdateAdopter(Adopter instance);
    partial void DeleteAdopter(Adopter instance);
    partial void InsertEmployee(Employee instance);
    partial void UpdateEmployee(Employee instance);
    partial void DeleteEmployee(Employee instance);
    #endregion
		
		public DataClasses1DataContext() : 
				base(global::HumaneSocietyProject.Properties.Settings.Default.AnimalsConnectionString, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(string connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public DataClasses1DataContext(System.Data.IDbConnection connection, System.Data.Linq.Mapping.MappingSource mappingSource) : 
				base(connection, mappingSource)
		{
			OnCreated();
		}
		
		public System.Data.Linq.Table<Animal> Animals
		{
			get
			{
				return this.GetTable<Animal>();
			}
		}
		
		public System.Data.Linq.Table<Adopter> Adopters
		{
			get
			{
				return this.GetTable<Adopter>();
			}
		}
		
		public System.Data.Linq.Table<Employee> Employees
		{
			get
			{
				return this.GetTable<Employee>();
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Animals")]
	public partial class Animal : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Animal_ID;
		
		private string _Type_Of;
		
		private string _Name;
		
		private System.Nullable<int> _Age;
		
		private System.Nullable<int> _Room_Location;
		
		private string _Food_Type;
		
		private System.Nullable<int> _Food_Amount;
		
		private System.Nullable<int> _Price_Of_Adoption;
		
		private System.Nullable<bool> _IsAdopted;
		
		private System.Nullable<bool> _HasShots;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnAnimal_IDChanging(int value);
    partial void OnAnimal_IDChanged();
    partial void OnType_OfChanging(string value);
    partial void OnType_OfChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnAgeChanging(System.Nullable<int> value);
    partial void OnAgeChanged();
    partial void OnRoom_LocationChanging(System.Nullable<int> value);
    partial void OnRoom_LocationChanged();
    partial void OnFood_TypeChanging(string value);
    partial void OnFood_TypeChanged();
    partial void OnFood_AmountChanging(System.Nullable<int> value);
    partial void OnFood_AmountChanged();
    partial void OnPrice_Of_AdoptionChanging(System.Nullable<int> value);
    partial void OnPrice_Of_AdoptionChanged();
    partial void OnIsAdoptedChanging(System.Nullable<bool> value);
    partial void OnIsAdoptedChanged();
    partial void OnHasShotsChanging(System.Nullable<bool> value);
    partial void OnHasShotsChanged();
    #endregion
		
		public Animal()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Animal_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Animal_ID
		{
			get
			{
				return this._Animal_ID;
			}
			set
			{
				if ((this._Animal_ID != value))
				{
					this.OnAnimal_IDChanging(value);
					this.SendPropertyChanging();
					this._Animal_ID = value;
					this.SendPropertyChanged("Animal_ID");
					this.OnAnimal_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type_Of", DbType="VarChar(MAX)")]
		public string Type_Of
		{
			get
			{
				return this._Type_Of;
			}
			set
			{
				if ((this._Type_Of != value))
				{
					this.OnType_OfChanging(value);
					this.SendPropertyChanging();
					this._Type_Of = value;
					this.SendPropertyChanged("Type_Of");
					this.OnType_OfChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Age", DbType="Int")]
		public System.Nullable<int> Age
		{
			get
			{
				return this._Age;
			}
			set
			{
				if ((this._Age != value))
				{
					this.OnAgeChanging(value);
					this.SendPropertyChanging();
					this._Age = value;
					this.SendPropertyChanged("Age");
					this.OnAgeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Room_Location", DbType="Int")]
		public System.Nullable<int> Room_Location
		{
			get
			{
				return this._Room_Location;
			}
			set
			{
				if ((this._Room_Location != value))
				{
					this.OnRoom_LocationChanging(value);
					this.SendPropertyChanging();
					this._Room_Location = value;
					this.SendPropertyChanged("Room_Location");
					this.OnRoom_LocationChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Food_Type", DbType="VarChar(MAX)")]
		public string Food_Type
		{
			get
			{
				return this._Food_Type;
			}
			set
			{
				if ((this._Food_Type != value))
				{
					this.OnFood_TypeChanging(value);
					this.SendPropertyChanging();
					this._Food_Type = value;
					this.SendPropertyChanged("Food_Type");
					this.OnFood_TypeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Food_Amount", DbType="Int")]
		public System.Nullable<int> Food_Amount
		{
			get
			{
				return this._Food_Amount;
			}
			set
			{
				if ((this._Food_Amount != value))
				{
					this.OnFood_AmountChanging(value);
					this.SendPropertyChanging();
					this._Food_Amount = value;
					this.SendPropertyChanged("Food_Amount");
					this.OnFood_AmountChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Price_Of_Adoption", DbType="Int")]
		public System.Nullable<int> Price_Of_Adoption
		{
			get
			{
				return this._Price_Of_Adoption;
			}
			set
			{
				if ((this._Price_Of_Adoption != value))
				{
					this.OnPrice_Of_AdoptionChanging(value);
					this.SendPropertyChanging();
					this._Price_Of_Adoption = value;
					this.SendPropertyChanged("Price_Of_Adoption");
					this.OnPrice_Of_AdoptionChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_IsAdopted", DbType="Bit")]
		public System.Nullable<bool> IsAdopted
		{
			get
			{
				return this._IsAdopted;
			}
			set
			{
				if ((this._IsAdopted != value))
				{
					this.OnIsAdoptedChanging(value);
					this.SendPropertyChanging();
					this._IsAdopted = value;
					this.SendPropertyChanged("IsAdopted");
					this.OnIsAdoptedChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasShots", DbType="Bit")]
		public System.Nullable<bool> HasShots
		{
			get
			{
				return this._HasShots;
			}
			set
			{
				if ((this._HasShots != value))
				{
					this.OnHasShotsChanging(value);
					this.SendPropertyChanging();
					this._HasShots = value;
					this.SendPropertyChanged("HasShots");
					this.OnHasShotsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Adopter")]
	public partial class Adopter : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Person_ID;
		
		private string _Name;
		
		private string _Home_Address;
		
		private string _Type_Of_Home;
		
		private System.Nullable<bool> _Owns_Other_Pets;
		
		private string _Primary_Veteranarian;
		
		private System.Nullable<bool> _HasChildren;
		
		private string _LifeStyle_and_Activity_Levels;
		
		private string _Experience_With_Previous_Pets;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnPerson_IDChanging(int value);
    partial void OnPerson_IDChanged();
    partial void OnNameChanging(string value);
    partial void OnNameChanged();
    partial void OnHome_AddressChanging(string value);
    partial void OnHome_AddressChanged();
    partial void OnType_Of_HomeChanging(string value);
    partial void OnType_Of_HomeChanged();
    partial void OnOwns_Other_PetsChanging(System.Nullable<bool> value);
    partial void OnOwns_Other_PetsChanged();
    partial void OnPrimary_VeteranarianChanging(string value);
    partial void OnPrimary_VeteranarianChanged();
    partial void OnHasChildrenChanging(System.Nullable<bool> value);
    partial void OnHasChildrenChanged();
    partial void OnLifeStyle_and_Activity_LevelsChanging(string value);
    partial void OnLifeStyle_and_Activity_LevelsChanged();
    partial void OnExperience_With_Previous_PetsChanging(string value);
    partial void OnExperience_With_Previous_PetsChanged();
    #endregion
		
		public Adopter()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Person_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Person_ID
		{
			get
			{
				return this._Person_ID;
			}
			set
			{
				if ((this._Person_ID != value))
				{
					this.OnPerson_IDChanging(value);
					this.SendPropertyChanging();
					this._Person_ID = value;
					this.SendPropertyChanged("Person_ID");
					this.OnPerson_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Name", DbType="VarChar(MAX)")]
		public string Name
		{
			get
			{
				return this._Name;
			}
			set
			{
				if ((this._Name != value))
				{
					this.OnNameChanging(value);
					this.SendPropertyChanging();
					this._Name = value;
					this.SendPropertyChanged("Name");
					this.OnNameChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Home_Address", DbType="VarChar(MAX)")]
		public string Home_Address
		{
			get
			{
				return this._Home_Address;
			}
			set
			{
				if ((this._Home_Address != value))
				{
					this.OnHome_AddressChanging(value);
					this.SendPropertyChanging();
					this._Home_Address = value;
					this.SendPropertyChanged("Home_Address");
					this.OnHome_AddressChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Type_Of_Home", DbType="VarChar(MAX)")]
		public string Type_Of_Home
		{
			get
			{
				return this._Type_Of_Home;
			}
			set
			{
				if ((this._Type_Of_Home != value))
				{
					this.OnType_Of_HomeChanging(value);
					this.SendPropertyChanging();
					this._Type_Of_Home = value;
					this.SendPropertyChanged("Type_Of_Home");
					this.OnType_Of_HomeChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Owns_Other_Pets", DbType="Bit")]
		public System.Nullable<bool> Owns_Other_Pets
		{
			get
			{
				return this._Owns_Other_Pets;
			}
			set
			{
				if ((this._Owns_Other_Pets != value))
				{
					this.OnOwns_Other_PetsChanging(value);
					this.SendPropertyChanging();
					this._Owns_Other_Pets = value;
					this.SendPropertyChanged("Owns_Other_Pets");
					this.OnOwns_Other_PetsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Primary_Veteranarian", DbType="VarChar(MAX)")]
		public string Primary_Veteranarian
		{
			get
			{
				return this._Primary_Veteranarian;
			}
			set
			{
				if ((this._Primary_Veteranarian != value))
				{
					this.OnPrimary_VeteranarianChanging(value);
					this.SendPropertyChanging();
					this._Primary_Veteranarian = value;
					this.SendPropertyChanged("Primary_Veteranarian");
					this.OnPrimary_VeteranarianChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_HasChildren", DbType="Bit")]
		public System.Nullable<bool> HasChildren
		{
			get
			{
				return this._HasChildren;
			}
			set
			{
				if ((this._HasChildren != value))
				{
					this.OnHasChildrenChanging(value);
					this.SendPropertyChanging();
					this._HasChildren = value;
					this.SendPropertyChanged("HasChildren");
					this.OnHasChildrenChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_LifeStyle_and_Activity_Levels", DbType="VarChar(MAX)")]
		public string LifeStyle_and_Activity_Levels
		{
			get
			{
				return this._LifeStyle_and_Activity_Levels;
			}
			set
			{
				if ((this._LifeStyle_and_Activity_Levels != value))
				{
					this.OnLifeStyle_and_Activity_LevelsChanging(value);
					this.SendPropertyChanging();
					this._LifeStyle_and_Activity_Levels = value;
					this.SendPropertyChanged("LifeStyle_and_Activity_Levels");
					this.OnLifeStyle_and_Activity_LevelsChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Experience_With_Previous_Pets", DbType="VarChar(MAX)")]
		public string Experience_With_Previous_Pets
		{
			get
			{
				return this._Experience_With_Previous_Pets;
			}
			set
			{
				if ((this._Experience_With_Previous_Pets != value))
				{
					this.OnExperience_With_Previous_PetsChanging(value);
					this.SendPropertyChanging();
					this._Experience_With_Previous_Pets = value;
					this.SendPropertyChanged("Experience_With_Previous_Pets");
					this.OnExperience_With_Previous_PetsChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
	
	[global::System.Data.Linq.Mapping.TableAttribute(Name="dbo.Employee")]
	public partial class Employee : INotifyPropertyChanging, INotifyPropertyChanged
	{
		
		private static PropertyChangingEventArgs emptyChangingEventArgs = new PropertyChangingEventArgs(String.Empty);
		
		private int _Employee_ID;
		
		private string _Employee_Name;
		
    #region Extensibility Method Definitions
    partial void OnLoaded();
    partial void OnValidate(System.Data.Linq.ChangeAction action);
    partial void OnCreated();
    partial void OnEmployee_IDChanging(int value);
    partial void OnEmployee_IDChanged();
    partial void OnEmployee_NameChanging(string value);
    partial void OnEmployee_NameChanged();
    #endregion
		
		public Employee()
		{
			OnCreated();
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_ID", AutoSync=AutoSync.OnInsert, DbType="Int NOT NULL IDENTITY", IsPrimaryKey=true, IsDbGenerated=true)]
		public int Employee_ID
		{
			get
			{
				return this._Employee_ID;
			}
			set
			{
				if ((this._Employee_ID != value))
				{
					this.OnEmployee_IDChanging(value);
					this.SendPropertyChanging();
					this._Employee_ID = value;
					this.SendPropertyChanged("Employee_ID");
					this.OnEmployee_IDChanged();
				}
			}
		}
		
		[global::System.Data.Linq.Mapping.ColumnAttribute(Storage="_Employee_Name", DbType="VarChar(MAX)")]
		public string Employee_Name
		{
			get
			{
				return this._Employee_Name;
			}
			set
			{
				if ((this._Employee_Name != value))
				{
					this.OnEmployee_NameChanging(value);
					this.SendPropertyChanging();
					this._Employee_Name = value;
					this.SendPropertyChanged("Employee_Name");
					this.OnEmployee_NameChanged();
				}
			}
		}
		
		public event PropertyChangingEventHandler PropertyChanging;
		
		public event PropertyChangedEventHandler PropertyChanged;
		
		protected virtual void SendPropertyChanging()
		{
			if ((this.PropertyChanging != null))
			{
				this.PropertyChanging(this, emptyChangingEventArgs);
			}
		}
		
		protected virtual void SendPropertyChanged(String propertyName)
		{
			if ((this.PropertyChanged != null))
			{
				this.PropertyChanged(this, new PropertyChangedEventArgs(propertyName));
			}
		}
	}
}
#pragma warning restore 1591
